### ISSUE TITLE
Hosting Issue

### ISSUE THREAD

**Issue by Kushal-kothari** [Anagha-2000/PsychHelp.github.io#1]
I think you can't make hosting to any repository. Github  only allows hosting if the domain is your name or the organisation 
Eg:  PsychHelp.github.io   : this wont work

Anagha-2000.github.io : this will work

What you can instead do is host the website on your own domain and create a page to use PsychHelp as aPortfolio
Eg:Anagha-2000.github.io/PsychHelp

This should work :)

**Comment by Anagha-2000** [comment]
yeah, I got that.  The thing is GitHub only hosts static websites so this one won't work as it is being made in react. I'll try hosting it on Heroku. The problem is not hosting, but the oAuth issue. otherwise, it is already hosted on netlify.

**Comment by Anagha-2000** [comment]
i'll delete this repo.

**Comment by Kushal-kothari** [comment]
Cool :)
